DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'openclub_app') THEN
    CREATE ROLE openclub_app WITH LOGIN PASSWORD 'your-secure-password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE openclub TO openclub_app;
GRANT USAGE ON SCHEMA public TO openclub_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO openclub_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO openclub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO openclub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO openclub_app;
