FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm --filter=backend run build

FROM base AS runner
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/apps/backend/dist ./dist
COPY --from=build /usr/src/app/apps/backend/package.json ./package.json
COPY --from=build /usr/src/app/node_modules ./node_modules
# Prisma requires the schema at runtime in a monorepo setup
COPY --from=build /usr/src/app/database/prisma/schema.prisma ./database/prisma/schema.prisma
EXPOSE 3001
CMD ["node", "dist/main"]
