FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build --filter=web-admin

FROM base AS runner
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/apps/web-admin/.next ./.next
COPY --from=build /usr/src/app/apps/web-admin/public ./public
COPY --from=build /usr/src/app/apps/web-admin/package.json ./package.json
COPY --from=build /usr/src/app/node_modules ./node_modules
EXPOSE 3000
CMD ["pnpm", "start"]
