FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm --filter=web-admin run build

FROM base AS runner
WORKDIR /usr/src/app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=build /usr/src/app/apps/web-admin/public ./apps/web-admin/public
COPY --from=build /usr/src/app/apps/web-admin/.next/standalone ./
COPY --from=build /usr/src/app/apps/web-admin/.next/static ./apps/web-admin/.next/static

EXPOSE 3000
CMD ["node", "apps/web-admin/server.js"]
